-- Crear usuario administrador
CREATE USER admin_facturacion IDENTIFIED BY Admin123;
GRANT CONNECT, RESOURCE, DBA TO admin_facturacion;

-- Crear usuario con permisos específicos
CREATE USER usuario_consulta IDENTIFIED BY Usuario123;
GRANT CONNECT, RESOURCE TO usuario_consulta;

-- Crear rol de administrador
CREATE ROLE ROLE_DBA_FACTURACION;

-- Otorgar todos los privilegios al rol
GRANT ALL PRIVILEGES TO ROLE_DBA_FACTURACION;

-- Asignar rol a admin_facturacion
GRANT CONNECT TO admin_facturacion;
GRANT ROLE_DBA_FACTURACION TO admin_facturacion;

-- Crear rol con permisos limitados
CREATE ROLE ROLE_OPERADOR_FACTURACION;

-- Otorgar permisos a cada tabla del esquema ADMIN_FACTURACION
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.CAJA TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.USUARIO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.TIPO_USUARIO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.PRODUCTO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.CATEGORIA TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.EMPLEADO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.PUESTO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.SALARIOS TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.FACTURACION TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.REABASTECIMIENTO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.REPORTE TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.TIENDA TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.INVENTARIO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.DIRECCION TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.PROVINCIA TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.CANTON TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.DISTRITO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.CORREO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.TELEFONO TO ROLE_OPERADOR_FACTURACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADMIN_FACTURACION.FIDELIZACION TO ROLE_OPERADOR_FACTURACION;

-- Crear usuario operador y asignar rol
CREATE USER operador_facturacion IDENTIFIED BY Operador123;
GRANT CONNECT TO operador_facturacion;
GRANT ROLE_OPERADOR_FACTURACION TO operador_facturacion;